// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCpKjcDaKGfiXkHxNqa___Q6tb2Wwr1N4',
    appId: '1:975314281355:web:d11a79fd1ebe19f015058e',
    messagingSenderId: '975314281355',
    projectId: 'tes-navios',
    authDomain: 'tes-navios.firebaseapp.com',
    storageBucket: 'tes-navios.appspot.com',
    measurementId: 'G-NR98V04F44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGtJldMuD06-l_sUf5UBEwlPPJ_zZ-wk',
    appId: '1:975314281355:android:5c8cbfcdabbf32c215058e',
    messagingSenderId: '975314281355',
    projectId: 'tes-navios',
    storageBucket: 'tes-navios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxKFKYP9bKYtk8AXyKlFXCePhx9IsnC-k',
    appId: '1:975314281355:ios:90ff0a2d5715bd2d15058e',
    messagingSenderId: '975314281355',
    projectId: 'tes-navios',
    storageBucket: 'tes-navios.appspot.com',
    iosBundleId: 'com.example.mobileTes',
  );
}
